spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/projects/spring/junstagram/db/junstagram # 윈도우
    url: jdbc:h2:tcp://localhost/~/Documents/projects/spring/junstargram/db/junstargram # 맥
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # sql 쿼리 로그에 파라미터를 남김